# Site Settings
name: Teddy-woo's DevOps Challenge!
title: 도현's Blog | 도현's 데브옵스 도전기!
description: 도현's 데브옵스 도전기! is made by
  Teddy-woo.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: 배포 자동화
    url: /category/배포%20자동화/
  - title: 지속적 통합
    url: /category/지속적%20통합/
  - title: DOCKER(도커)
    url: /category/Docker/
  - title: 아마존 웹 서비스(AWS)
    url: /category/아마존%20웹%20서비스(AWS)/
  - title: 트러블 슈팅
    url: /category/트러블%20슈팅/
  - title: YAML과 JSON
    url: /category/YAML과%20JSON/
  - title: 웹 서버 프로그램
    url: /category/웹%20서버%20프로그램/
  - title: 네트워크 기초
    url: /category/네트워크%20기초/
  - title: 프로젝트 회고
    url: /category/프로젝트%20회고/
  - title: 데이터베이스
    url: /category/데이터베이스/
  - title: WAS와 WEB SERVER
    url: /category/WAS와%20WEB%20SERVER/
  - title: HTTP
    url: /category/HTTP/
  - title: (사전준비) 개발 환경 구축
    url: /category/(사전준비)%20개발%20환경%20구축/
  - title: GIT과 버전 관리 시스템
    url: /category/GIT과%20버전%20관리%20시스템/
  - title: 웹서비스 개발 기초
    url: /category/웹서비스%20개발%20기초/
  - title: 리눅스 운영체제
    url: /category/리눅스%20운영체제
  - title: 개발 프로세스와 DEVOPS 업무
    url: /category/개발%20프로세스와%20DEVOPS%20업무/
email: dnehgus6975@gmail.com
# See: https://disqus.com/
disqus_username: teddynote
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 


# Social Media Settings
# Remove the item if you don't need it
github_username: teddy-woo
# facebook_username: facebook_username
# twitter_username: twitter_username
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "G-YQQ2NQ44TG"
language: "ko"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2
